version: 2

project_name: NoLetS

builds:
  - id: darwin
    main: .
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    env:
      - CGO_ENABLED=0

  - id: linux
    main: .
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - mips64
      - mips64le
    goamd64:
      - v2
      - v3
      - v4
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    env:
      - CGO_ENABLED=0

  - id: windows
    main: .
    goos:
      - windows
    goarch:
      - amd64
    goamd64:
      - v2
      - v3
      - v4
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    env:
      - CGO_ENABLED=0

  - id: freebsd
    main: .
    goos:
      - freebsd
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    format: tar.gz
    files:
      - src: pushback.p8
        dst: pushback.p8
      - LICENSE
      - README.md
      - README_EN.md
      - README_JP.md
      - README_KR.md


release:
  github:
    owner: sunvc
    name: NoLetServer

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
